---
name: Pre-commit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  pre-commit:
    uses: "Mosher-Labs/.github/.github/workflows/pre-commit.yml@39dc1e003e0c99ee009eecca4773bb6aa4935ce2"  # v0.11.1
    permissions:
      contents: read
