---
name: Pre-commit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  pre-commit:
    uses: "Mosher-Labs/.github/.github/workflows/pre-commit.yml@e101c2025370aa3e6a223fade898845db2c75171"  # v0.10.38
    permissions:
      contents: read
